### ISSUE TITLE
Can't use hyprpaper

### ISSUE THREAD

**Issue by SIERRA-880** [charludo/nix#1]
I found your repo by reading issues on the home-manager github. It helped me a lot for my configuration because your's is not too complicated. Thanks a lot!

I can't get Hyprpaper to work, when I run the command `hyprpaper` I get `The program 'hyprpaper' is not in your PATH.` However, I have `services.hyprpaper.enable = true` in my configuration. I did the exact same thing as for `hyprlock` who is working perfectly so I don't understand my problem.

Thank you for any help :)

**Comment by charludo** [comment]
Hi!

> It helped me a lot for my configuration because your's is not too complicated. Thanks a lot!

Glad to hear it, although I feel obligated to point out that a lot of my config was ~stolen from~ inspired by [Misterio77/nix-config](https://github.com/Misterio77/nix-config).

I just checked, and indeed do get the same error messages when trying to execute `hyprpaper` manually. Does the service get started properly for you (check `systemctl --user status hyprpaper`)?

If you really want/need the program in your path, I guess you could just add `home.packages = [ pkgs.hyprpaper ];` somewhere.
